# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='descrip',
            new_name='descript',
        ),
    ]
